name = "neovim"
description = "neovim + lazy.nvim config"
tags = ["essential"]
depends_on = ["git", "asdf"]

[[packages]]
manager = "pacman"
names = ["neovim", "lazygit", "ripgrep", "fd", "unzip", "tree-sitter-cli", "imagemagick", "mermaid-cli"]

[[symlinks]]
src = "files/nvim"
dst = "~/.config/nvim"
