set -g @thm_bg "#191724"
set -g @thm_surface_0 "#1f1d2e"
set -g @thm_overlay_0 "#6e6a86"
set -g @thm_rosewater "#e0def4"
set -g @thm_red "#eb6f92"
set -g @thm_maroon "#ebbcba"
set -g @thm_peach "#ebbcba"
set -g @thm_yellow "#f6c177"
set -g @thm_green "#9ccfd8"
set -g @thm_blue "#31748f"
set -g @thm_mauve "#c4a7e7"
set -g @thm_pink "#c4a7e7"
set -g @thm_fg "#e0def4"
set -g @thm_mantle "#191724"
set -g @thm_crust "#191724"
set -g @thm_surface_1 "#403d52"
set -g @thm_teal "#9ccfd8"
set -g @thm_lavender "#c4a7e7"
