set -g @thm_bg "#0a0a0a"
set -g @thm_surface_0 "#1f1f1f"
set -g @thm_overlay_0 "#141414"
set -g @thm_rosewater "#e6e6e6"
set -g @thm_red "#555555"
set -g @thm_maroon "#666666"
set -g @thm_peach "#666666"
set -g @thm_yellow "#777777"
set -g @thm_green "#888888"
set -g @thm_blue "#aaaaaa"
set -g @thm_mauve "#bbbbbb"
set -g @thm_pink "#bbbbbb"
