set -g @thm_bg "#2e3440"
set -g @thm_surface_0 "#434c5e"
set -g @thm_overlay_0 "#616e88"
set -g @thm_rosewater "#d8dee9"
set -g @thm_red "#bf616a"
set -g @thm_maroon "#d08770"
set -g @thm_peach "#d08770"
set -g @thm_yellow "#ebcb8b"
set -g @thm_green "#a3be8c"
set -g @thm_blue "#5e81ac"
set -g @thm_mauve "#b48ead"
set -g @thm_pink "#b48ead"
