set -g @thm_bg "#1a1b26"
set -g @thm_surface_0 "#283457"
set -g @thm_overlay_0 "#545c7e"
set -g @thm_rosewater "#c0caf5"
set -g @thm_red "#f7768e"
set -g @thm_maroon "#ff9e64"
set -g @thm_peach "#ff9e64"
set -g @thm_yellow "#e0af68"
set -g @thm_green "#9ece6a"
set -g @thm_blue "#7aa2f7"
set -g @thm_mauve "#bb9af7"
set -g @thm_pink "#bb9af7"
set -g @thm_fg "#c0caf5"
set -g @thm_mantle "#1a1b26"
set -g @thm_crust "#1a1b26"
set -g @thm_surface_1 "#414868"
set -g @thm_teal "#7dcfff"
set -g @thm_lavender "#bb9af7"
