name = "archlaptop"
modules = ["git", "shell", "tmux", "fonts", "asdf", "neovim", "hyprland", "ai"]

[vars]
git_email = "50755420+DaltonDayton@users.noreply.github.com"
git_signing_key = "~/.ssh/id_ed25519"
