set -g @thm_bg "#e6e6e6"
set -g @thm_surface_0 "#c4c4c4"
set -g @thm_overlay_0 "#888888"
set -g @thm_rosewater "#2b2b2b"
set -g @thm_red "#0a0a0a"
set -g @thm_maroon "#363636"
set -g @thm_peach "#0a0a0a"
set -g @thm_yellow "#555555"
set -g @thm_green "#363636"
set -g @thm_blue "#454545"
set -g @thm_mauve "#555555"
set -g @thm_pink "#666666"
