set -g @thm_bg "#272e33"
set -g @thm_surface_0 "#374145"
set -g @thm_overlay_0 "#7a8478"
set -g @thm_rosewater "#d3c6aa"
set -g @thm_red "#e67e80"
set -g @thm_maroon "#e69875"
set -g @thm_peach "#e69875"
set -g @thm_yellow "#dbbc7f"
set -g @thm_green "#a7c080"
set -g @thm_blue "#7fbbb3"
set -g @thm_mauve "#d699b6"
set -g @thm_pink "#d699b6"
set -g @thm_fg "#d3c6aa"
set -g @thm_mantle "#272e33"
set -g @thm_crust "#272e33"
set -g @thm_surface_1 "#414b50"
set -g @thm_teal "#83c092"
set -g @thm_lavender "#d699b6"
