name = "solaar"
description = "Logitech Unifying receiver manager + udev rule"
tags = ["apps"]
os   = ["arch"]

[[packages]]
manager = "pacman"
names = ["solaar"]

[[symlinks]]
src = "files/config"
dst = "~/.config/solaar"
