name    = "arch-laptop"
os      = "arch"
machine = "laptop"
modules = ["git", "shell", "tmux", "fonts", "asdf", "python", "neovim", "hyprland", "ai", "obsidian", "solaar"]

[vars]
git_email = "50755420+DaltonDayton@users.noreply.github.com"
git_signing_key = "~/.ssh/id_ed25519"
