set -g @thm_bg "#192330"
set -g @thm_surface_0 "#2b3b51"
set -g @thm_overlay_0 "#738091"
set -g @thm_rosewater "#cdcecf"
set -g @thm_red "#c94f6d"
set -g @thm_maroon "#f4a261"
set -g @thm_peach "#f4a261"
set -g @thm_yellow "#dbc074"
set -g @thm_green "#8ebaa4"
set -g @thm_blue "#719cd6"
set -g @thm_mauve "#baa1e2"
set -g @thm_pink "#baa1e2"
