set -g @thm_bg "#192330"
set -g @thm_surface_0 "#313b48"
set -g @thm_overlay_0 "#495360"
set -g @thm_rosewater "#c0c8d5"
set -g @thm_red "#c94f6d"
set -g @thm_maroon "#fe9373"
set -g @thm_peach "#fe9373"
set -g @thm_yellow "#dbc074"
set -g @thm_green "#8ebaa4"
set -g @thm_blue "#719cd6"
set -g @thm_mauve "#baa1e2"
set -g @thm_pink "#baa1e2"
