background  {{palettes.neutral._5.hex}}
foreground  {{colors.on_surface.dark.hex}}
cursor      {{colors.on_surface.dark.hex}}

color0  {{palettes.neutral._5.hex}}
color1  {{palettes.error._80.hex}}
color2  {{palettes.primary._80.hex}}
color3  {{palettes.tertiary._90.hex}}
color4  {{palettes.secondary._70.hex}}
color5  {{palettes.primary._90.hex}}
color6  {{palettes.secondary._90.hex}}
color7  {{colors.on_surface.dark.hex}}

color8  {{colors.outline_variant.dark.hex}}
color9  {{palettes.error._80.hex}}
color10 {{palettes.primary._80.hex}}
color11 {{palettes.tertiary._90.hex}}
color12 {{palettes.secondary._70.hex}}
color13 {{palettes.primary._90.hex}}
color14 {{palettes.secondary._90.hex}}
color15 {{colors.on_surface.dark.hex}}
