background  {{palettes.neutral._5.hex}}
foreground  {{colors.on_surface.dark.hex}}
cursor      {{colors.on_surface.dark.hex}}
cursor_text_color {{palettes.neutral._5.hex}}

selection_foreground {{colors.on_surface.dark.hex}}
selection_background {{palettes.neutral._20.hex}}

url_color {{colors.secondary.default.hex}}

active_tab_foreground   {{palettes.neutral._5.hex}}
active_tab_background   {{colors.primary.default.hex}}
inactive_tab_foreground {{colors.outline.default.hex}}
inactive_tab_background {{palettes.neutral._10.hex}}
tab_bar_background      {{palettes.neutral._5.hex}}

active_border_color   {{colors.primary.default.hex}}
inactive_border_color {{colors.outline_variant.dark.hex}}

color0  {{palettes.neutral._5.hex}}
color1  {{colors.error.default.hex}}
color2  {{colors.primary.default.hex}}
color3  {{colors.tertiary_fixed.default.hex}}
color4  {{colors.secondary.default.hex}}
color5  {{colors.primary_fixed.default.hex}}
color6  {{colors.secondary_fixed.default.hex}}
color7  {{colors.on_surface.dark.hex}}

color8  {{colors.outline_variant.dark.hex}}
color9  {{colors.error.default.hex}}
color10 {{colors.primary.default.hex}}
color11 {{colors.tertiary_fixed.default.hex}}
color12 {{colors.secondary.default.hex}}
color13 {{colors.primary_fixed.default.hex}}
color14 {{colors.secondary_fixed.default.hex}}
color15 {{colors.on_surface.dark.hex}}
