-- Generated by matugen. Do not edit by hand.
-- Self-applying Neovim colorscheme using the canonical theme vocabulary.

vim.cmd("hi clear")
if vim.g.syntax_on then vim.cmd("syntax reset") end
vim.g.colors_name = "matugen"

local p = {
  bg0    = "{{palettes.neutral._5.hex}}",
  bg1    = "{{palettes.neutral._10.hex}}",
  bg2    = "{{palettes.neutral._15.hex}}",
  bg3    = "{{palettes.neutral._20.hex}}",
  bg4    = "{{palettes.neutral._25.hex}}",
  fg     = "{{colors.on_surface.default.hex}}",
  red    = "{{colors.error.default.hex}}",
  orange = "{{colors.tertiary.default.hex}}",
  yellow = "{{colors.tertiary_fixed.default.hex}}",
  green  = "{{colors.primary.default.hex}}",
  aqua   = "{{colors.secondary_fixed.default.hex}}",
  blue   = "{{colors.secondary.default.hex}}",
  purple = "{{colors.primary_fixed.default.hex}}",
  grey0  = "{{colors.outline_variant.default.hex}}",
  grey1  = "{{colors.outline.default.hex}}",
  grey2  = "{{colors.on_surface_variant.default.hex}}",
}

local hi = vim.api.nvim_set_hl
local function set(group, opts) hi(0, group, opts) end

-- UI
set("Normal",        { fg = p.fg, bg = p.bg0 })
set("NormalNC",      { fg = p.fg, bg = p.bg0 })
set("NonText",       { fg = p.bg4 })
set("Whitespace",    { fg = p.bg3 })
set("EndOfBuffer",   { fg = p.bg1 })
set("NormalFloat",   { fg = p.fg })
set("FloatBorder",   { fg = p.bg4 })
set("CursorLine",    { bg = p.bg2 })
set("CursorLineNr",  { fg = p.fg, bold = true })
set("LineNr",        { fg = p.grey1 })
set("SignColumn",    { bg = p.bg0 })
set("VertSplit",     { fg = p.bg4 })
set("WinSeparator",  { fg = p.bg4 })
set("Visual",        { bg = p.bg3 })
set("StatusLine",    { fg = p.fg, bg = p.bg1 })
set("StatusLineNC",  { fg = p.grey1, bg = p.bg1 })
set("Pmenu",         { fg = p.fg, bg = p.bg1 })
set("PmenuSel",      { fg = p.bg0, bg = p.blue })
set("PmenuThumb",    { bg = p.bg3 })
set("MatchParen",    { bg = p.bg3, bold = true })
set("Search",        { fg = p.bg0, bg = p.yellow })
set("IncSearch",     { fg = p.bg0, bg = p.orange })
set("Folded",        { fg = p.grey1, bg = p.bg1 })

-- Syntax
set("Comment",     { fg = p.grey1, italic = true })
set("Identifier",  { fg = p.fg })
set("Function",    { fg = p.green })
set("Statement",   { fg = p.purple })
set("Keyword",     { fg = p.purple })
set("String",      { fg = p.aqua })
set("Number",      { fg = p.orange })
set("Boolean",     { fg = p.orange })
set("Constant",    { fg = p.orange })
set("Type",        { fg = p.yellow })
set("PreProc",     { fg = p.purple })
set("Special",     { fg = p.red })
set("Operator",    { fg = p.fg })
set("Delimiter",   { fg = p.grey2 })
set("Title",       { fg = p.blue, bold = true })

-- Diagnostics
set("DiagnosticError",   { fg = p.red })
set("DiagnosticWarn",    { fg = p.yellow })
set("DiagnosticInfo",    { fg = p.blue })
set("DiagnosticHint",    { fg = p.aqua })
set("DiagnosticOk",      { fg = p.green })

-- Diff / git
set("DiffAdd",     { fg = p.green })
set("DiffChange",  { fg = p.yellow })
set("DiffDelete",  { fg = p.red })
set("GitSignsAdd",    { fg = p.green })
set("GitSignsChange", { fg = p.yellow })
set("GitSignsDelete", { fg = p.red })

-- Treesitter (links)
set("@variable",    { fg = p.fg })
set("@function",    { link = "Function" })
set("@keyword",     { link = "Keyword" })
set("@string",      { link = "String" })
set("@number",      { link = "Number" })
set("@type",        { link = "Type" })
set("@comment",     { link = "Comment" })
set("@operator",    { link = "Operator" })
set("@punctuation", { fg = p.grey2 })

-- The `hi clear` above wiped plugin-defined groups (gitsigns blame, etc.).
-- Applying via dofile skips the ColorScheme event, so fire it manually to
-- let plugins re-derive their highlights.
vim.api.nvim_exec_autocmds("ColorScheme", { pattern = "matugen", modeline = false })
