$bg0 = rgb(1e1e2e)
$bg1 = rgb(313244)
$bg2 = rgb(45475a)
$bg3 = rgb(585b70)
$bg4 = rgb(6c7086)

$red    = rgb(f38ba8)
$orange = rgb(fab387)
$yellow = rgb(f9e2af)
$green  = rgb(a6e3a1)
$aqua   = rgb(94e2d5)
$blue   = rgb(89b4fa)
$purple = rgb(cba6f7)

$fg = rgb(cdd6f4)

$grey0 = rgb(7f849c)
$grey1 = rgb(9399b2)
$grey2 = rgb(a6adc8)
