set -g @thm_bg "#1f1f28"
set -g @thm_surface_0 "#223249"
set -g @thm_overlay_0 "#54546d"
set -g @thm_rosewater "#dcd7ba"
set -g @thm_red "#e82424"
set -g @thm_maroon "#ffa066"
set -g @thm_peach "#ffa066"
set -g @thm_yellow "#dca561"
set -g @thm_green "#98bb6c"
set -g @thm_blue "#7e9cd8"
set -g @thm_mauve "#957fb8"
set -g @thm_pink "#957fb8"
set -g @thm_fg "#dcd7ba"
set -g @thm_mantle "#1f1f28"
set -g @thm_crust "#1f1f28"
set -g @thm_surface_1 "#363646"
set -g @thm_teal "#7aa89f"
set -g @thm_lavender "#957fb8"
