set -g @thm_bg "#1F1F28"
set -g @thm_surface_0 "#223249"
set -g @thm_overlay_0 "#54546D"
set -g @thm_rosewater "#DCD7BA"
set -g @thm_red "#E82424"
set -g @thm_maroon "#FFA066"
set -g @thm_peach "#FFA066"
set -g @thm_yellow "#DCA561"
set -g @thm_green "#98BB6C"
set -g @thm_blue "#7E9CD8"
set -g @thm_mauve "#957FB8"
set -g @thm_pink "#957FB8"
