set -g @thm_bg "#1d2021"
set -g @thm_surface_0 "#3c3836"
set -g @thm_overlay_0 "#928374"
set -g @thm_rosewater "#ebdbb2"
set -g @thm_red "#cc241d"
set -g @thm_maroon "#fb4934"
set -g @thm_peach "#d65d0e"
set -g @thm_yellow "#d79921"
set -g @thm_green "#98971a"
set -g @thm_blue "#458588"
set -g @thm_mauve "#b16286"
set -g @thm_pink "#d3869b"
