# Laptop — built-in display
monitor=eDP-1,preferred,auto,2

# Laptop GPU workaround
env = AQ_NO_MODIFIERS,1

# Acer Z35P ultrawide
monitor=desc:Acer Technologies Z35P T3ZAA0038511,3440x1440@50,auto,1

# Fallback — auto-detect any other connected monitors
monitor=,preferred,auto,1

